using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;


public class PokemonList : MonoBehaviour
{
    //ALL LISTS WILL BE IN NATIONAL POKEDEX ORDER

    //This list is used to grab Sprites
    //MAKE SURE TO USE .TOLOWER()
    public static List<string> pokemonIDs = new List<string>
            {
                "None",
                "Bulbasaur",
                "Ivysaur",
                "Venusaur",
                "Charmander",
                "Charmeleon",
                "Charizard",
                "Squirtle",
                "Wartortle",
                "Blastoise",
                "Caterpie",
                "Metapod",
                "Butterfree",
                "Weedle",
                "Kakuna",
                "Beedrill",
                "Pidgey",
                "Pidgeotto",
                "Pidgeot",
                "Rattata",
                "Raticate",
                "Spearow",
                "Fearow",
                "Ekans",
                "Arbok",
                "Pikachu",
                "Raichu",
                "Sandshrew",
                "Sandslash",
                "Nidoranf",
                "Nidorina",
                "Nidoqueen",
                "Nidoranm",
                "Nidorino",
                "Nidoking",
                "Clefairy",
                "Clefable",
                "Vulpix",
                "Ninetales",
                "Jigglypuff",
                "Wigglytuff",
                "Zubat",
                "Golbat",
                "Oddish",
                "Gloom",
                "Vileplume",
                "Paras",
                "Parasect",
                "Venonat",
                "Venomoth",
                "Diglett",
                "Dugtrio",
                "Meowth",
                "Persian",
                "Psyduck",
                "Golduck",
                "Mankey",
                "Primeape",
                "Growlithe",
                "Arcanine",
                "Poliwag",
                "Poliwhirl",
                "Poliwrath",
                "Abra",
                "Kadabra",
                "Alakazam",
                "Machop",
                "Machoke",
                "Machamp",
                "Bellsprout",
                "Weepinbell",
                "Victreebel",
                "Tentacool",
                "Tentacruel",
                "Geodude",
                "Graveler",
                "Golem",
                "Ponyta",
                "Rapidash",
                "Slowpoke",
                "Slowbro",
                "Magnemite",
                "Magneton",
                "Farfetchd",
                "Doduo",
                "Dodrio",
                "Seel",
                "Dewgong",
                "Grimer",
                "Muk",
                "Shellder",
                "Cloyster",
                "Gastly",
                "Haunter",
                "Gengar",
                "Onix",
                "Drowzee",
                "Hypno",
                "Krabby",
                "Kingler",
                "Voltorb",
                "Electrode",
                "Exeggcute",
                "Exeggutor",
                "Cubone",
                "Marowak",
                "Hitmonlee",
                "Hitmonchan",
                "Lickitung",
                "Koffing",
                "Weezing",
                "Rhyhorn",
                "Rhydon",
                "Chansey",
                "Tangela",
                "Kangaskhan",
                "Horsea",
                "Seadra",
                "Goldeen",
                "Seaking",
                "Staryu",
                "Starmie",
                "MrMime",
                "Scyther",
                "Jynx",
                "Electabuzz",
                "Magmar",
                "Pinsir",
                "Tauros",
                "Magikarp",
                "Gyarados",
                "Lapras",
                "Ditto",
                "Eevee",
                "Vaporeon",
                "Jolteon",
                "Flareon",
                "Porygon",
                "Omanyte",
                "Omastar",
                "Kabuto",
                "Kabutops",
                "Aerodactyl",
                "Snorlax",
                "Articuno",
                "Zapdos",
                "Moltres",
                "Dratini",
                "Dragonair",
                "Dragonite",
                "Mewtwo",
                "Mew",
                "Chikorita",
                "Bayleef",
                "Meganium",
                "Cyndaquil",
                "Quilava",
                "Typhlosion",
                "Totodile",
                "Croconaw",
                "Feraligatr",
                "Sentret",
                "Furret",
                "Hoothoot",
                "Noctowl",
                "Ledyba",
                "Ledian",
                "Spinarak",
                "Ariados",
                "Crobat",
                "Chinchou",
                "Lanturn",
                "Pichu",
                "Cleffa",
                "Igglybuff",
                "Togepi",
                "Togetic",
                "Natu",
                "Xatu",
                "Mareep",
                "Flaaffy",
                "Ampharos",
                "Bellossom",
                "Marill",
                "Azumarill",
                "Sudowoodo",
                "Politoed",
                "Hoppip",
                "Skiploom",
                "Jumpluff",
                "Aipom",
                "Sunkern",
                "Sunflora",
                "Yanma",
                "Wooper",
                "Quagsire",
                "Espeon",
                "Umbreon",
                "Murkrow",
                "Slowking",
                "Misdreavus",
                "Unown",
                "Wobbuffet",
                "Girafarig",
                "Pineco",
                "Forretress",
                "Dunsparce",
                "Gligar",
                "Steelix",
                "Snubbull",
                "Granbull",
                "Qwilfish",
                "Scizor",
                "Shuckle",
                "Heracross",
                "Sneasel",
                "Teddiursa",
                "Ursaring",
                "Slugma",
                "Magcargo",
                "Swinub",
                "Piloswine",
                "Corsola",
                "Remoraid",
                "Octillery",
                "Delibird",
                "Mantine",
                "Skarmory",
                "Houndour",
                "Houndoom",
                "Kingdra",
                "Phanpy",
                "Donphan",
                "Porygon2",
                "Stantler",
                "Smeargle",
                "Tyrogue",
                "Hitmontop",
                "Smoochum",
                "Elekid",
                "Magby",
                "Miltank",
                "Blissey",
                "Raikou",
                "Entei",
                "Suicune",
                "Larvitar",
                "Pupitar",
                "Tyranitar",
                "Lugia",
                "Hooh",
                "Celebi",
                "Treecko",
                "Grovyle",
                "Sceptile",
                "Torchic",
                "Combusken",
                "Blaziken",
                "Mudkip",
                "Marshtomp",
                "Swampert",
                "Poochyena",
                "Mightyena",
                "Zigzagoon",
                "Linoone",
                "Wurmple",
                "Silcoon",
                "Beautifly",
                "Cascoon",
                "Dustox",
                "Lotad",
                "Lombre",
                "Ludicolo",
                "Seedot",
                "Nuzleaf",
                "Shiftry",
                "Taillow",
                "Swellow",
                "Wingull",
                "Pelipper",
                "Ralts",
                "Kirlia",
                "Gardevoir",
                "Surskit",
                "Masquerain",
                "Shroomish",
                "Breloom",
                "Slakoth",
                "Vigoroth",
                "Slaking",
                "Nincada",
                "Ninjask",
                "Shedinja",
                "Whismur",
                "Loudred",
                "Exploud",
                "Makuhita",
                "Hariyama",
                "Azurill",
                "Nosepass",
                "Skitty",
                "Delcatty",
                "Sableye",
                "Mawile",
                "Aron",
                "Lairon",
                "Aggron",
                "Meditite",
                "Medicham",
                "Electrike",
                "Manectric",
                "Plusle",
                "Minun",
                "Volbeat",
                "Illumise",
                "Roselia",
                "Gulpin",
                "Swalot",
                "Carvanha",
                "Sharpedo",
                "Wailmer",
                "Wailord",
                "Numel",
                "Camerupt",
                "Torkoal",
                "Spoink",
                "Grumpig",
                "Spinda",
                "Trapinch",
                "Vibrava",
                "Flygon",
                "Cacnea",
                "Cacturne",
                "Swablu",
                "Altaria",
                "Zangoose",
                "Seviper",
                "Lunatone",
                "Solrock",
                "Barboach",
                "Whiscash",
                "Corphish",
                "Crawdaunt",
                "Baltoy",
                "Claydol",
                "Lileep",
                "Cradily",
                "Anorith",
                "Armaldo",
                "Feebas",
                "Milotic",
                "Castform",
                "Kecleon",
                "Shuppet",
                "Banette",
                "Duskull",
                "Dusclops",
                "Tropius",
                "Chimecho",
                "Absol",
                "Wynaut",
                "Snorunt",
                "Glalie",
                "Spheal",
                "Sealeo",
                "Walrein",
                "Clamperl",
                "Huntail",
                "Gorebyss",
                "Relicanth",
                "Luvdisc",
                "Bagon",
                "Shelgon",
                "Salamence",
                "Beldum",
                "Metang",
                "Metagross",
                "Regirock",
                "Regice",
                "Registeel",
                "Latias",
                "Latios",
                "Kyogre",
                "Groudon",
                "Rayquaza",
                "Jirachi",
                "Deoxys",
                "Turtwig",
                "Grotle",
                "Torterra",
                "Chimchar",
                "Monferno",
                "Infernape",
                "Piplup",
                "Prinplup",
                "Empoleon",
                "Starly",
                "Staravia",
                "Staraptor",
                "Bidoof",
                "Bibarel",
                "Kricketot",
                "Kricketune",
                "Shinx",
                "Luxio",
                "Luxray",
                "Budew",
                "Roserade",
                "Cranidos",
                "Rampardos",
                "Shieldon",
                "Bastiodon",
                "Burmy",
                "Wormadam",
                "Mothim",
                "Combee",
                "Vespiquen",
                "Pachirisu",
                "Buizel",
                "Floatzel",
                "Cherubi",
                "Cherrim",
                "Shellos",
                "Gastrodon",
                "Ambipom",
                "Drifloon",
                "Drifblim",
                "Buneary",
                "Lopunny",
                "Mismagius",
                "Honchkrow",
                "Glameow",
                "Purugly",
                "Chingling",
                "Stunky",
                "Skuntank",
                "Bronzor",
                "Bronzong",
                "Bonsly",
                "MimeJr",
                "Happiny",
                "Chatot",
                "Spiritomb",
                "Gible",
                "Gabite",
                "Garchomp",
                "Munchlax",
                "Riolu",
                "Lucario",
                "Hippopotas",
                "Hippowdon",
                "Skorupi",
                "Drapion",
                "Croagunk",
                "Toxicroak",
                "Carnivine",
                "Finneon",
                "Lumineon",
                "Mantyke",
                "Snover",
                "Abomasnow",
                "Weavile",
                "Magnezone",
                "Lickilicky",
                "Rhyperior",
                "Tangrowth",
                "Electivire",
                "Magmortar",
                "Togekiss",
                "Yanmega",
                "Leafeon",
                "Glaceon",
                "Gliscor",
                "Mamoswine",
                "PorygonZ",
                "Gallade",
                "Probopass",
                "Dusknoir",
                "Froslass",
                "Rotom",
                "Uxie",
                "Mesprit",
                "Azelf",
                "Dialga",
                "Palkia",
                "Heatran",
                "Regigigas",
                "Giratina",
                "Cresselia",
                "Phione",
                "Manaphy",
                "Darkrai",
                "Shaymin",
                "Arceus",
                "Victini",
                "Snivy",
                "Servine",
                "Serperior",
                "Tepig",
                "Pignite",
                "Emboar",
                "Oshawott",
                "Dewott",
                "Samurott",
                "Patrat",
                "Watchog",
                "Lillipup",
                "Herdier",
                "Stoutland",
                "Purrloin",
                "Liepard",
                "Pansage",
                "Simisage",
                "Pansear",
                "Simisear",
                "Panpour",
                "Simipour",
                "Munna",
                "Musharna",
                "Pidove",
                "Tranquill",
                "Unfezant",
                "Blitzle",
                "Zebstrika",
                "Roggenrola",
                "Boldore",
                "Gigalith",
                "Woobat",
                "Swoobat",
                "Drilbur",
                "Excadrill",
                "Audino",
                "Timburr",
                "Gurdurr",
                "Conkeldurr",
                "Tympole",
                "Palpitoad",
                "Seismitoad",
                "Throh",
                "Sawk",
                "Sewaddle",
                "Swadloon",
                "Leavanny",
                "Venipede",
                "Whirlipede",
                "Scolipede",
                "Cottonee",
                "Whimsicott",
                "Petilil",
                "Lilligant",
                "Basculin",
                "Sandile",
                "Krokorok",
                "Krookodile",
                "Darumaka",
                "Darmanitan",
                "Maractus",
                "Dwebble",
                "Crustle",
                "Scraggy",
                "Scrafty",
                "Sigilyph",
                "Yamask",
                "Cofagrigus",
                "Tirtouga",
                "Carracosta",
                "Archen",
                "Archeops",
                "Trubbish",
                "Garbodor",
                "Zorua",
                "Zoroark",
                "Minccino",
                "Cinccino",
                "Gothita",
                "Gothorita",
                "Gothitelle",
                "Solosis",
                "Duosion",
                "Reuniclus",
                "Ducklett",
                "Swanna",
                "Vanillite",
                "Vanillish",
                "Vanilluxe",
                "Deerling",
                "Sawsbuck",
                "Emolga",
                "Karrablast",
                "Escavalier",
                "Foongus",
                "Amoonguss",
                "Frillish",
                "Jellicent",
                "Alomomola",
                "Joltik",
                "Galvantula",
                "Ferroseed",
                "Ferrothorn",
                "Klink",
                "Klang",
                "Klinklang",
                "Tynamo",
                "Eelektrik",
                "Eelektross",
                "Elgyem",
                "Beheeyem",
                "Litwick",
                "Lampent",
                "Chandelure",
                "Axew",
                "Fraxure",
                "Haxorus",
                "Cubchoo",
                "Beartic",
                "Cryogonal",
                "Shelmet",
                "Accelgor",
                "Stunfisk",
                "Mienfoo",
                "Mienshao",
                "Druddigon",
                "Golett",
                "Golurk",
                "Pawniard",
                "Bisharp",
                "Bouffalant",
                "Rufflet",
                "Braviary",
                "Vullaby",
                "Mandibuzz",
                "Heatmor",
                "Durant",
                "Deino",
                "Zweilous",
                "Hydreigon",
                "Larvesta",
                "Volcarona",
                "Cobalion",
                "Terrakion",
                "Virizion",
                "Tornadus",
                "Thundurus",
                "Reshiram",
                "Zekrom",
                "Landorus",
                "Kyurem",
                "Keldeo",
                "Meloetta",
                "Genesect",
                "Chespin",
                "Quilladin",
                "Chesnaught",
                "Fennekin",
                "Braixen",
                "Delphox",
                "Froakie",
                "Frogadier",
                "Greninja",
                "Bunnelby",
                "Diggersby",
                "Fletchling",
                "Fletchinder",
                "Talonflame",
                "Scatterbug",
                "Spewpa",
                "Vivillon",
                "Litleo",
                "Pyroar",
                "Flabebe",
                "Floette",
                "Florges",
                "Skiddo",
                "Gogoat",
                "Pancham",
                "Pangoro",
                "Furfrou",
                "Espurr",
                "Meowstic",
                "Honedge",
                "Doublade",
                "Aegislash",
                "Spritzee",
                "Aromatisse",
                "Swirlix",
                "Slurpuff",
                "Inkay",
                "Malamar",
                "Binacle",
                "Barbaracle",
                "Skrelp",
                "Dragalge",
                "Clauncher",
                "Clawitzer",
                "Helioptile",
                "Heliolisk",
                "Tyrunt",
                "Tyrantrum",
                "Amaura",
                "Aurorus",
                "Sylveon",
                "Hawlucha",
                "Dedenne",
                "Carbink",
                "Goomy",
                "Sliggoo",
                "Goodra",
                "Klefki",
                "Phantump",
                "Trevenant",
                "Pumpkaboo",
                "Gourgeist",
                "Bergmite",
                "Avalugg",
                "Noibat",
                "Noivern",
                "Xerneas",
                "Yveltal",
                "Zygarde",
                "Diancie",
                "Hoopa",
                "Volcanion",
                "Rowlet",
                "Dartrix",
                "Decidueye",
                "Litten",
                "Torracat",
                "Incineroar",
                "Popplio",
                "Brionne",
                "Primarina",
                "Pikipek",
                "Trumbeak",
                "Toucannon",
                "Yungoos",
                "Gumshoos",
                "Grubbin",
                "Charjabug",
                "Vikavolt",
                "Crabrawler",
                "Crabominable",
                "Oricorio",
                "Cutiefly",
                "Ribombee",
                "Rockruff",
                "Lycanroc",
                "Wishiwashi",
                "Mareanie",
                "Toxapex",
                "Mudbray",
                "Mudsdale",
                "Dewpider",
                "Araquanid",
                "Fomantis",
                "Lurantis",
                "Morelull",
                "Shiinotic",
                "Salandit",
                "Salazzle",
                "Stufful",
                "Bewear",
                "Bounsweet",
                "Steenee",
                "Tsareena",
                "Comfey",
                "Oranguru",
                "Passimian",
                "Wimpod",
                "Golisopod",
                "Sandygast",
                "Palossand",
                "Pyukumuku",
                "TypeNull",
                "Silvally",
                "Minior",
                "Komala",
                "Turtonator",
                "Togedemaru",
                "Mimikyu",
                "Bruxish",
                "Drampa",
                "Dhelmise",
                "Jangmoo",
                "Hakamoo",
                "Kommoo",
                "TapuKoko",
                "TapuLele",
                "TapuBulu",
                "TapuFini",
                "Cosmog",
                "Cosmoem",
                "Solgaleo",
                "Lunala",
                "Nihilego",
                "Buzzwole",
                "Pheromosa",
                "Xurkitree",
                "Celesteela",
                "Kartana",
                "Guzzlord",
                "Necrozma",
                "Magearna",
                "Marshadow",
                "Poipole",
                "Naganadel",
                "Stakataka",
                "Blacephalon",
                "Zeraora",
                "Meltan",
                "Melmetal",
                "Grookey",
                "Thwackey",
                "Rillaboom",
                "Scorbunny",
                "Raboot",
                "Cinderace",
                "Sobble",
                "Drizzile",
                "Inteleon",
                "Skwovet",
                "Greedent",
                "Rookidee",
                "Corvisquire",
                "Corviknight",
                "Blipbug",
                "Dottler",
                "Orbeetle",
                "Nickit",
                "Thievul",
                "Gossifleur",
                "Eldegoss",
                "Wooloo",
                "Dubwool",
                "Chewtle",
                "Drednaw",
                "Yamper",
                "Boltund",
                "Rolycoly",
                "Carkol",
                "Coalossal",
                "Applin",
                "Flapple",
                "Appletun",
                "Silicobra",
                "Sandaconda",
                "Cramorant",
                "Arrokuda",
                "Barraskewda",
                "Toxel",
                "Toxtricity",
                "Sizzlipede",
                "Centiskorch",
                "Clobbopus",
                "Grapploct",
                "Sinistea",
                "Polteageist",
                "Hatenna",
                "Hattrem",
                "Hatterene",
                "Impidimp",
                "Morgrem",
                "Grimmsnarl",
                "Obstagoon",
                "Perrserker",
                "Cursola",
                "Sirfetchd",
                "MrRime",
                "Runerigus",
                "Milcery",
                "Alcremie",
                "Falinks",
                "Pincurchin",
                "Snom",
                "Frosmoth",
                "Stonjourner",
                "Eiscue",
                "Indeedee",
                "Morpeko",
                "Cufant",
                "Copperajah",
                "Dracozolt",
                "Arctozolt",
                "Dracovish",
                "Arctovish",
                "Duraludon",
                "Dreepy",
                "Drakloak",
                "Dragapult",
                "Zacian",
                "Zamazenta",
                "Eternatus",
                "Kubfu",
                "Urshifu",
                "Zarude",
                "Regieleki",
                "Regidrago",
                "Glastrier",
                "Spectrier",
                "Calyrex",
                "Wyrdeer",
                "Kleavor",
                "Ursaluna",
                "Basculegion",
                "Sneasler",
                "Overqwil",
                "Enamorus",
                "Sprigatito",
                "Floragato",
                "Meowscarada",
                "Fuecoco",
                "Crocalor",
                "Skeledirge",
                "Quaxly",
                "Quaxwell",
                "Quaquaval",
                "Lechonk",
                "Oinkologne",
                "Tarountula",
                "Spidops",
                "Nymble",
                "Lokix",
                "Pawmi",
                "Pawmo",
                "Pawmot",
                "Tandemaus",
                "Maushold",
                "Fidough",
                "Dachsbun",
                "Smoliv",
                "Dolliv",
                "Arboliva",
                "Squawkabilly",
                "Nacli",
                "Naclstack",
                "Garganacl",
                "Charcadet",
                "Armarouge",
                "Ceruledge",
                "Tadbulb",
                "Bellibolt",
                "Wattrel",
                "Kilowattrel",
                "Maschiff",
                "Mabosstiff",
                "Shroodle",
                "Grafaiai",
                "Bramblin",
                "Brambleghast",
                "Toedscool",
                "Toedscruel",
                "Klawf",
                "Capsakid",
                "Scovillain",
                "Rellor",
                "Rabsca",
                "Flittle",
                "Espathra",
                "Tinkatink",
                "Tinkatuff",
                "Tinkaton",
                "Wiglett",
                "Wugtrio",
                "Bombirdier",
                "Finizen",
                "Palafin",
                "Varoom",
                "Revavroom",
                "Cyclizar",
                "Orthworm",
                "Glimmet",
                "Glimmora",
                "Greavard",
                "Houndstone",
                "Flamigo",
                "Cetoddle",
                "Cetitan",
                "Veluza",
                "Dondozo",
                "Tatsugiri",
                "Annihilape",
                "Clodsire",
                "Farigiraf",
                "Dudunsparce",
                "Kingambit",
                "GreatTusk",
                "ScreamTail",
                "BruteBonnet",
                "FlutterMane",
                "SlitherWing",
                "SandyShocks",
                "IronTreads",
                "IronBundle",
                "IronHands",
                "IronJugulis",
                "IronMoth",
                "IronThorns",
                "Frigibax",
                "Arctibax",
                "Baxcalibur",
                "Gimmighoul",
                "Gholdengo",
                "WoChien",
                "ChienPao",
                "TingLu",
                "ChiYu",
                "RoaringMoon",
                "IronValiant",
                "Koraidon",
                "Miraidon",
                "WalkingWake",
                "IronLeaves",
                "Dipplin",
                "Poltchageist",
                "Sinistcha",
                "Okidogi",
                "Munkidori",
                "Fezandipiti",
                "Ogerpon",
                "Archaludon",
                "Hydrapple",
                "GougingFire",
                "RagingBolt",
                "IronBoulder",
                "IronCrown",
                "Terapagos",
                "Pecharunt"
            };
    //This list is used to show the Pokemon's Name on the UI
    public static List<string> pokemonNames = new List<string>
    {
        "None",
        "Bulbasaur",
        "Ivysaur",
        "Venusaur",
        "Charmander",
        "Charmeleon",
        "Charizard",
        "Squirtle",
        "Wartortle",
        "Blastoise",
        "Caterpie",
        "Metapod",
        "Butterfree",
        "Weedle",
        "Kakuna",
        "Beedrill",
        "Pidgey",
        "Pidgeotto",
        "Pidgeot",
        "Rattata",
        "Raticate",
        "Spearow",
        "Fearow",
        "Ekans",
        "Arbok",
        "Pikachu",
        "Raichu",
        "Sandshrew",
        "Sandslash",
        "Nidoran-f",
        "Nidorina",
        "Nidoqueen",
        "Nidoran-m",
        "Nidorino",
        "Nidoking",
        "Clefairy",
        "Clefable",
        "Vulpix",
        "Ninetales",
        "Jigglypuff",
        "Wigglytuff",
        "Zubat",
        "Golbat",
        "Oddish",
        "Gloom",
        "Vileplume",
        "Paras",
        "Parasect",
        "Venonat",
        "Venomoth",
        "Diglett",
        "Dugtrio",
        "Meowth",
        "Persian",
        "Psyduck",
        "Golduck",
        "Mankey",
        "Primeape",
        "Growlithe",
        "Arcanine",
        "Poliwag",
        "Poliwhirl",
        "Poliwrath",
        "Abra",
        "Kadabra",
        "Alakazam",
        "Machop",
        "Machoke",
        "Machamp",
        "Bellsprout",
        "Weepinbell",
        "Victreebel",
        "Tentacool",
        "Tentacruel",
        "Geodude",
        "Graveler",
        "Golem",
        "Ponyta",
        "Rapidash",
        "Slowpoke",
        "Slowbro",
        "Magnemite",
        "Magneton",
        "Farfetch\'d",
        "Doduo",
        "Dodrio",
        "Seel",
        "Dewgong",
        "Grimer",
        "Muk",
        "Shellder",
        "Cloyster",
        "Gastly",
        "Haunter",
        "Gengar",
        "Onix",
        "Drowzee",
        "Hypno",
        "Krabby",
        "Kingler",
        "Voltorb",
        "Electrode",
        "Exeggcute",
        "Exeggutor",
        "Cubone",
        "Marowak",
        "Hitmonlee",
        "Hitmonchan",
        "Lickitung",
        "Koffing",
        "Weezing",
        "Rhyhorn",
        "Rhydon",
        "Chansey",
        "Tangela",
        "Kangaskhan",
        "Horsea",
        "Seadra",
        "Goldeen",
        "Seaking",
        "Staryu",
        "Starmie",
        "Mr. Mime",
        "Scyther",
        "Jynx",
        "Electabuzz",
        "Magmar",
        "Pinsir",
        "Tauros",
        "Magikarp",
        "Gyarados",
        "Lapras",
        "Ditto",
        "Eevee",
        "Vaporeon",
        "Jolteon",
        "Flareon",
        "Porygon",
        "Omanyte",
        "Omastar",
        "Kabuto",
        "Kabutops",
        "Aerodactyl",
        "Snorlax",
        "Articuno",
        "Zapdos",
        "Moltres",
        "Dratini",
        "Dragonair",
        "Dragonite",
        "Mewtwo",
        "Mew",
        "Chikorita",
        "Bayleef",
        "Meganium",
        "Cyndaquil",
        "Quilava",
        "Typhlosion",
        "Totodile",
        "Croconaw",
        "Feraligatr",
        "Sentret",
        "Furret",
        "Hoothoot",
        "Noctowl",
        "Ledyba",
        "Ledian",
        "Spinarak",
        "Ariados",
        "Crobat",
        "Chinchou",
        "Lanturn",
        "Pichu",
        "Cleffa",
        "Igglybuff",
        "Togepi",
        "Togetic",
        "Natu",
        "Xatu",
        "Mareep",
        "Flaaffy",
        "Ampharos",
        "Bellossom",
        "Marill",
        "Azumarill",
        "Sudowoodo",
        "Politoed",
        "Hoppip",
        "Skiploom",
        "Jumpluff",
        "Aipom",
        "Sunkern",
        "Sunflora",
        "Yanma",
        "Wooper",
        "Quagsire",
        "Espeon",
        "Umbreon",
        "Murkrow",
        "Slowking",
        "Misdreavus",
        "Unown",
        "Wobbuffet",
        "Girafarig",
        "Pineco",
        "Forretress",
        "Dunsparce",
        "Gligar",
        "Steelix",
        "Snubbull",
        "Granbull",
        "Qwilfish",
        "Scizor",
        "Shuckle",
        "Heracross",
        "Sneasel",
        "Teddiursa",
        "Ursaring",
        "Slugma",
        "Magcargo",
        "Swinub",
        "Piloswine",
        "Corsola",
        "Remoraid",
        "Octillery",
        "Delibird",
        "Mantine",
        "Skarmory",
        "Houndour",
        "Houndoom",
        "Kingdra",
        "Phanpy",
        "Donphan",
        "Porygon2",
        "Stantler",
        "Smeargle",
        "Tyrogue",
        "Hitmontop",
        "Smoochum",
        "Elekid",
        "Magby",
        "Miltank",
        "Blissey",
        "Raikou",
        "Entei",
        "Suicune",
        "Larvitar",
        "Pupitar",
        "Tyranitar",
        "Lugia",
        "Ho-oh",
        "Celebi",
        "Treecko",
        "Grovyle",
        "Sceptile",
        "Torchic",
        "Combusken",
        "Blaziken",
        "Mudkip",
        "Marshtomp",
        "Swampert",
        "Poochyena",
        "Mightyena",
        "Zigzagoon",
        "Linoone",
        "Wurmple",
        "Silcoon",
        "Beautifly",
        "Cascoon",
        "Dustox",
        "Lotad",
        "Lombre",
        "Ludicolo",
        "Seedot",
        "Nuzleaf",
        "Shiftry",
        "Taillow",
        "Swellow",
        "Wingull",
        "Pelipper",
        "Ralts",
        "Kirlia",
        "Gardevoir",
        "Surskit",
        "Masquerain",
        "Shroomish",
        "Breloom",
        "Slakoth",
        "Vigoroth",
        "Slaking",
        "Nincada",
        "Ninjask",
        "Shedinja",
        "Whismur",
        "Loudred",
        "Exploud",
        "Makuhita",
        "Hariyama",
        "Azurill",
        "Nosepass",
        "Skitty",
        "Delcatty",
        "Sableye",
        "Mawile",
        "Aron",
        "Lairon",
        "Aggron",
        "Meditite",
        "Medicham",
        "Electrike",
        "Manectric",
        "Plusle",
        "Minun",
        "Volbeat",
        "Illumise",
        "Roselia",
        "Gulpin",
        "Swalot",
        "Carvanha",
        "Sharpedo",
        "Wailmer",
        "Wailord",
        "Numel",
        "Camerupt",
        "Torkoal",
        "Spoink",
        "Grumpig",
        "Spinda",
        "Trapinch",
        "Vibrava",
        "Flygon",
        "Cacnea",
        "Cacturne",
        "Swablu",
        "Altaria",
        "Zangoose",
        "Seviper",
        "Lunatone",
        "Solrock",
        "Barboach",
        "Whiscash",
        "Corphish",
        "Crawdaunt",
        "Baltoy",
        "Claydol",
        "Lileep",
        "Cradily",
        "Anorith",
        "Armaldo",
        "Feebas",
        "Milotic",
        "Castform",
        "Kecleon",
        "Shuppet",
        "Banette",
        "Duskull",
        "Dusclops",
        "Tropius",
        "Chimecho",
        "Absol",
        "Wynaut",
        "Snorunt",
        "Glalie",
        "Spheal",
        "Sealeo",
        "Walrein",
        "Clamperl",
        "Huntail",
        "Gorebyss",
        "Relicanth",
        "Luvdisc",
        "Bagon",
        "Shelgon",
        "Salamence",
        "Beldum",
        "Metang",
        "Metagross",
        "Regirock",
        "Regice",
        "Registeel",
        "Latias",
        "Latios",
        "Kyogre",
        "Groudon",
        "Rayquaza",
        "Jirachi",
        "Deoxys",
        "Turtwig",
        "Grotle",
        "Torterra",
        "Chimchar",
        "Monferno",
        "Infernape",
        "Piplup",
        "Prinplup",
        "Empoleon",
        "Starly",
        "Staravia",
        "Staraptor",
        "Bidoof",
        "Bibarel",
        "Kricketot",
        "Kricketune",
        "Shinx",
        "Luxio",
        "Luxray",
        "Budew",
        "Roserade",
        "Cranidos",
        "Rampardos",
        "Shieldon",
        "Bastiodon",
        "Burmy",
        "Wormadam",
        "Mothim",
        "Combee",
        "Vespiquen",
        "Pachirisu",
        "Buizel",
        "Floatzel",
        "Cherubi",
        "Cherrim",
        "Shellos",
        "Gastrodon",
        "Ambipom",
        "Drifloon",
        "Drifblim",
        "Buneary",
        "Lopunny",
        "Mismagius",
        "Honchkrow",
        "Glameow",
        "Purugly",
        "Chingling",
        "Stunky",
        "Skuntank",
        "Bronzor",
        "Bronzong",
        "Bonsly",
        "Mime Jr.",
        "Happiny",
        "Chatot",
        "Spiritomb",
        "Gible",
        "Gabite",
        "Garchomp",
        "Munchlax",
        "Riolu",
        "Lucario",
        "Hippopotas",
        "Hippowdon",
        "Skorupi",
        "Drapion",
        "Croagunk",
        "Toxicroak",
        "Carnivine",
        "Finneon",
        "Lumineon",
        "Mantyke",
        "Snover",
        "Abomasnow",
        "Weavile",
        "Magnezone",
        "Lickilicky",
        "Rhyperior",
        "Tangrowth",
        "Electivire",
        "Magmortar",
        "Togekiss",
        "Yanmega",
        "Leafeon",
        "Glaceon",
        "Gliscor",
        "Mamoswine",
        "Porygon-Z",
        "Gallade",
        "Probopass",
        "Dusknoir",
        "Froslass",
        "Rotom",
        "Uxie",
        "Mesprit",
        "Azelf",
        "Dialga",
        "Palkia",
        "Heatran",
        "Regigigas",
        "Giratina",
        "Cresselia",
        "Phione",
        "Manaphy",
        "Darkrai",
        "Shaymin",
        "Arceus",
        "Victini",
        "Snivy",
        "Servine",
        "Serperior",
        "Tepig",
        "Pignite",
        "Emboar",
        "Oshawott",
        "Dewott",
        "Samurott",
        "Patrat",
        "Watchog",
        "Lillipup",
        "Herdier",
        "Stoutland",
        "Purrloin",
        "Liepard",
        "Pansage",
        "Simisage",
        "Pansear",
        "Simisear",
        "Panpour",
        "Simipour",
        "Munna",
        "Musharna",
        "Pidove",
        "Tranquill",
        "Unfezant",
        "Blitzle",
        "Zebstrika",
        "Roggenrola",
        "Boldore",
        "Gigalith",
        "Woobat",
        "Swoobat",
        "Drilbur",
        "Excadrill",
        "Audino",
        "Timburr",
        "Gurdurr",
        "Conkeldurr",
        "Tympole",
        "Palpitoad",
        "Seismitoad",
        "Throh",
        "Sawk",
        "Sewaddle",
        "Swadloon",
        "Leavanny",
        "Venipede",
        "Whirlipede",
        "Scolipede",
        "Cottonee",
        "Whimsicott",
        "Petilil",
        "Lilligant",
        "Basculin",
        "Sandile",
        "Krokorok",
        "Krookodile",
        "Darumaka",
        "Darmanitan",
        "Maractus",
        "Dwebble",
        "Crustle",
        "Scraggy",
        "Scrafty",
        "Sigilyph",
        "Yamask",
        "Cofagrigus",
        "Tirtouga",
        "Carracosta",
        "Archen",
        "Archeops",
        "Trubbish",
        "Garbodor",
        "Zorua",
        "Zoroark",
        "Minccino",
        "Cinccino",
        "Gothita",
        "Gothorita",
        "Gothitelle",
        "Solosis",
        "Duosion",
        "Reuniclus",
        "Ducklett",
        "Swanna",
        "Vanillite",
        "Vanillish",
        "Vanilluxe",
        "Deerling",
        "Sawsbuck",
        "Emolga",
        "Karrablast",
        "Escavalier",
        "Foongus",
        "Amoonguss",
        "Frillish",
        "Jellicent",
        "Alomomola",
        "Joltik",
        "Galvantula",
        "Ferroseed",
        "Ferrothorn",
        "Klink",
        "Klang",
        "Klinklang",
        "Tynamo",
        "Eelektrik",
        "Eelektross",
        "Elgyem",
        "Beheeyem",
        "Litwick",
        "Lampent",
        "Chandelure",
        "Axew",
        "Fraxure",
        "Haxorus",
        "Cubchoo",
        "Beartic",
        "Cryogonal",
        "Shelmet",
        "Accelgor",
        "Stunfisk",
        "Mienfoo",
        "Mienshao",
        "Druddigon",
        "Golett",
        "Golurk",
        "Pawniard",
        "Bisharp",
        "Bouffalant",
        "Rufflet",
        "Braviary",
        "Vullaby",
        "Mandibuzz",
        "Heatmor",
        "Durant",
        "Deino",
        "Zweilous",
        "Hydreigon",
        "Larvesta",
        "Volcarona",
        "Cobalion",
        "Terrakion",
        "Virizion",
        "Tornadus",
        "Thundurus",
        "Reshiram",
        "Zekrom",
        "Landorus",
        "Kyurem",
        "Keldeo",
        "Meloetta",
        "Genesect",
        "Chespin",
        "Quilladin",
        "Chesnaught",
        "Fennekin",
        "Braixen",
        "Delphox",
        "Froakie",
        "Frogadier",
        "Greninja",
        "Bunnelby",
        "Diggersby",
        "Fletchling",
        "Fletchinder",
        "Talonflame",
        "Scatterbug",
        "Spewpa",
        "Vivillon",
        "Litleo",
        "Pyroar",
        "Flabebe",
        "Floette",
        "Florges",
        "Skiddo",
        "Gogoat",
        "Pancham",
        "Pangoro",
        "Furfrou",
        "Espurr",
        "Meowstic",
        "Honedge",
        "Doublade",
        "Aegislash",
        "Spritzee",
        "Aromatisse",
        "Swirlix",
        "Slurpuff",
        "Inkay",
        "Malamar",
        "Binacle",
        "Barbaracle",
        "Skrelp",
        "Dragalge",
        "Clauncher",
        "Clawitzer",
        "Helioptile",
        "Heliolisk",
        "Tyrunt",
        "Tyrantrum",
        "Amaura",
        "Aurorus",
        "Sylveon",
        "Hawlucha",
        "Dedenne",
        "Carbink",
        "Goomy",
        "Sliggoo",
        "Goodra",
        "Klefki",
        "Phantump",
        "Trevenant",
        "Pumpkaboo",
        "Gourgeist",
        "Bergmite",
        "Avalugg",
        "Noibat",
        "Noivern",
        "Xerneas",
        "Yveltal",
        "Zygarde",
        "Diancie",
        "Hoopa",
        "Volcanion",
        "Rowlet",
        "Dartrix",
        "Decidueye",
        "Litten",
        "Torracat",
        "Incineroar",
        "Popplio",
        "Brionne",
        "Primarina",
        "Pikipek",
        "Trumbeak",
        "Toucannon",
        "Yungoos",
        "Gumshoos",
        "Grubbin",
        "Charjabug",
        "Vikavolt",
        "Crabrawler",
        "Crabominable",
        "Oricorio",
        "Cutiefly",
        "Ribombee",
        "Rockruff",
        "Lycanroc",
        "Wishiwashi",
        "Mareanie",
        "Toxapex",
        "Mudbray",
        "Mudsdale",
        "Dewpider",
        "Araquanid",
        "Fomantis",
        "Lurantis",
        "Morelull",
        "Shiinotic",
        "Salandit",
        "Salazzle",
        "Stufful",
        "Bewear",
        "Bounsweet",
        "Steenee",
        "Tsareena",
        "Comfey",
        "Oranguru",
        "Passimian",
        "Wimpod",
        "Golisopod",
        "Sandygast",
        "Palossand",
        "Pyukumuku",
        "Type: Null",
        "Silvally",
        "Minior",
        "Komala",
        "Turtonator",
        "Togedemaru",
        "Mimikyu",
        "Bruxish",
        "Drampa",
        "Dhelmise",
        "Jangmo-o",
        "Hakamo-o",
        "Kommo-o",
        "Tapu Koko",
        "Tapu Lele",
        "Tapu Bulu",
        "Tapu Fini",
        "Cosmog",
        "Cosmoem",
        "Solgaleo",
        "Lunala",
        "Nihilego",
        "Buzzwole",
        "Pheromosa",
        "Xurkitree",
        "Celesteela",
        "Kartana",
        "Guzzlord",
        "Necrozma",
        "Magearna",
        "Marshadow",
        "Poipole",
        "Naganadel",
        "Stakataka",
        "Blacephalon",
        "Zeraora",
        "Meltan",
        "Melmetal",
        "Grookey",
        "Thwackey",
        "Rillaboom",
        "Scorbunny",
        "Raboot",
        "Cinderace",
        "Sobble",
        "Drizzile",
        "Inteleon",
        "Skwovet",
        "Greedent",
        "Rookidee",
        "Corvisquire",
        "Corviknight",
        "Blipbug",
        "Dottler",
        "Orbeetle",
        "Nickit",
        "Thievul",
        "Gossifleur",
        "Eldegoss",
        "Wooloo",
        "Dubwool",
        "Chewtle",
        "Drednaw",
        "Yamper",
        "Boltund",
        "Rolycoly",
        "Carkol",
        "Coalossal",
        "Applin",
        "Flapple",
        "Appletun",
        "Silicobra",
        "Sandaconda",
        "Cramorant",
        "Arrokuda",
        "Barraskewda",
        "Toxel",
        "Toxtricity",
        "Sizzlipede",
        "Centiskorch",
        "Clobbopus",
        "Grapploct",
        "Sinistea",
        "Polteageist",
        "Hatenna",
        "Hattrem",
        "Hatterene",
        "Impidimp",
        "Morgrem",
        "Grimmsnarl",
        "Obstagoon",
        "Perrserker",
        "Cursola",
        "Sirfetch\'d",
        "Mr. Rime",
        "Runerigus",
        "Milcery",
        "Alcremie",
        "Falinks",
        "Pincurchin",
        "Snom",
        "Frosmoth",
        "Stonjourner",
        "Eiscue",
        "Indeedee",
        "Morpeko",
        "Cufant",
        "Copperajah",
        "Dracozolt",
        "Arctozolt",
        "Dracovish",
        "Arctovish",
        "Duraludon",
        "Dreepy",
        "Drakloak",
        "Dragapult",
        "Zacian",
        "Zamazenta",
        "Eternatus",
        "Kubfu",
        "Urshifu",
        "Zarude",
        "Regieleki",
        "Regidrago",
        "Glastrier",
        "Spectrier",
        "Calyrex",
        "Wyrdeer",
        "Kleavor",
        "Ursaluna",
        "Basculegion",
        "Sneasler",
        "Overqwil",
        "Enamorus",
        "Sprigatito",
        "Floragato",
        "Meowscarada",
        "Fuecoco",
        "Crocalor",
        "Skeledirge",
        "Quaxly",
        "Quaxwell",
        "Quaquaval",
        "Lechonk",
        "Oinkologne",
        "Tarountula",
        "Spidops",
        "Nymble",
        "Lokix",
        "Pawmi",
        "Pawmo",
        "Pawmot",
        "Tandemaus",
        "Maushold",
        "Fidough",
        "Dachsbun",
        "Smoliv",
        "Dolliv",
        "Arboliva",
        "Squawkabilly",
        "Nacli",
        "Naclstack",
        "Garganacl",
        "Charcadet",
        "Armarouge",
        "Ceruledge",
        "Tadbulb",
        "Bellibolt",
        "Wattrel",
        "Kilowattrel",
        "Maschiff",
        "Mabosstiff",
        "Shroodle",
        "Grafaiai",
        "Bramblin",
        "Brambleghast",
        "Toedscool",
        "Toedscruel",
        "Klawf",
        "Capsakid",
        "Scovillain",
        "Rellor",
        "Rabsca",
        "Flittle",
        "Espathra",
        "Tinkatink",
        "Tinkatuff",
        "Tinkaton",
        "Wiglett",
        "Wugtrio",
        "Bombirdier",
        "Finizen",
        "Palafin",
        "Varoom",
        "Revavroom",
        "Cyclizar",
        "Orthworm",
        "Glimmet",
        "Glimmora",
        "Greavard",
        "Houndstone",
        "Flamigo",
        "Cetoddle",
        "Cetitan",
        "Veluza",
        "Dondozo",
        "Tatsugiri",
        "Annihilape",
        "Clodsire",
        "Farigiraf",
        "Dudunsparce",
        "Kingambit",
        "Great Tusk",
        "Scream Tail",
        "Brute Bonnet",
        "Flutter Mane",
        "Slither Wing",
        "Sandy Shocks",
        "Iron Treads",
        "Iron Bundle",
        "Iron Hands",
        "Iron Jugulis",
        "Iron Moth",
        "Iron Thorns",
        "Frigibax",
        "Arctibax",
        "Baxcalibur",
        "Gimmighoul",
        "Gholdengo",
        "Wo-Chien",
        "Chien-Pao",
        "Ting-Lu",
        "Chi-Yu",
        "Roaring Moon",
        "Iron Valiant",
        "Koraidon",
        "Miraidon",
        "Walking Wake",
        "Iron Leaves",
        "Dipplin",
        "Poltchageist",
        "Sinistcha",
        "Okidogi",
        "Munkidori",
        "Fezandipiti",
        "Ogerpon",
        "Archaludon",
        "Hydrapple",
        "Gouging Fire",
        "Raging Bolt",
        "Iron Boulder",
        "Iron Crown",
        "Terapagos",
        "Pecharunt"
    };

    public static List<List<PokemonType>> SuperEffectiveTypes = new List<List<PokemonType>>()
    {
        new(){}, //None
        new(){}, //Normal
        new(){PokemonType.Grass, PokemonType.Ice, PokemonType.Bug, PokemonType.Steel }, //Fire
        new(){PokemonType.Fire, PokemonType.Ground, PokemonType.Rock }, //Water
        new(){PokemonType.Water, PokemonType.Flying }, //Electric
        new(){PokemonType.Water, PokemonType.Ground, PokemonType.Rock }, //Grass
        new(){PokemonType.Grass, PokemonType.Ground, PokemonType.Flying, PokemonType.Dragon }, //Ice
        new(){PokemonType.Normal, PokemonType.Ice, PokemonType.Rock, PokemonType.Dark, PokemonType.Steel }, //Fighting
        new(){PokemonType.Grass, PokemonType.Fairy }, //Poison
        new(){PokemonType.Fire, PokemonType.Electric, PokemonType.Poison, PokemonType.Rock, PokemonType.Steel}, //Ground
        new(){PokemonType.Grass, PokemonType.Fighting, PokemonType.Bug }, //Flying
        new(){PokemonType.Fighting, PokemonType.Poison}, //Psychic
        new(){PokemonType.Grass, PokemonType.Psychic, PokemonType.Dark}, //Bug
        new(){PokemonType.Fire, PokemonType.Ice, PokemonType.Flying, PokemonType.Bug}, //Rock
        new(){PokemonType.Psychic, PokemonType.Ghost}, //Ghost
        new(){PokemonType.Dragon }, //Dragon
        new(){PokemonType.Psychic, PokemonType.Ghost }, //Dark
        new(){PokemonType.Ice, PokemonType.Rock, PokemonType.Fairy }, //Steel
        new(){PokemonType.Fighting, PokemonType.Dragon, PokemonType.Dark } //Fairy
    };
    public static List<List<PokemonType>> NotVeryEffectiveTypes = new List<List<PokemonType>>()
    {
        new(){}, //None
        new(){PokemonType.Rock, PokemonType.Steel }, //Normal
        new(){PokemonType.Fire, PokemonType.Water, PokemonType.Rock, PokemonType.Dragon}, //Fire
        new(){PokemonType.Water, PokemonType.Grass, PokemonType.Dragon }, //Water
        new(){PokemonType.Electric, PokemonType.Grass, PokemonType.Dragon }, //Electric
        new(){PokemonType.Fire, PokemonType.Grass, PokemonType.Poison, PokemonType.Flying, PokemonType.Bug, PokemonType.Dragon, PokemonType.Steel }, //Grass
        new(){PokemonType.Fire, PokemonType.Water, PokemonType.Ice, PokemonType.Steel }, //Ice
        new(){PokemonType.Poison, PokemonType.Flying, PokemonType.Psychic, PokemonType.Bug, PokemonType.Fairy }, //Fighting
        new(){PokemonType.Poison, PokemonType.Ground, PokemonType.Rock, PokemonType.Ghost }, //Poison
        new(){PokemonType.Grass, PokemonType.Bug}, //Ground
        new(){PokemonType.Electric, PokemonType.Rock, PokemonType.Steel }, //Flying
        new(){PokemonType.Psychic, PokemonType.Steel }, //Psychic
        new(){PokemonType.Fire, PokemonType.Fighting, PokemonType.Poison, PokemonType.Flying, PokemonType.Ghost, PokemonType.Steel, PokemonType.Fairy }, //Bug
        new(){PokemonType.Fighting, PokemonType.Ground, PokemonType.Steel }, //Rock
        new(){PokemonType.Dark }, //Ghost
        new(){PokemonType.Steel }, //Dragon
        new(){PokemonType.Fighting, PokemonType.Dark, PokemonType.Fairy }, //Dark
        new(){PokemonType.Fire, PokemonType.Water, PokemonType.Electric, PokemonType.Steel }, //Steel
        new(){PokemonType.Fire, PokemonType.Poison, PokemonType.Steel} //Fairy
    };
    public static List<List<PokemonType>> ImmuneTypes = new List<List<PokemonType>>()
    {
        new(){ }, //None
        new(){PokemonType.Ghost }, //Normal
        new(){ }, //Fire
        new(){ }, //Water
        new(){PokemonType.Ground }, //Electric
        new(){ }, //Grass
        new(){ }, //Ice
        new(){PokemonType.Ghost }, //Fighting
        new(){PokemonType.Steel }, //Poison
        new(){PokemonType.Flying }, //Ground
        new(){ }, //Flying
        new(){PokemonType.Dark }, //Psychic
        new(){ }, //Bug
        new(){ }, //Rock
        new(){PokemonType.Normal }, //Ghost
        new(){PokemonType.Fairy }, //Dragon
        new(){ }, //Dark
        new(){ }, //Steel
        new(){ } //Fairy
    };
    public static List<BallType> BallTypes = new List<BallType>()
    {
        new("PokeBall", 1),
        new("Great Ball", 1.5f),
        new("Ultra Ball", 2),
        new("Master Ball", 0)
    };
    public static List<Pokemon> PokemonData = new List<Pokemon>()
    {
        new(0, 0, EvolveMethod.None, 0, PokemonType.None, PokemonType.None),
        new(1, 16, EvolveMethod.LevelUp, 2, PokemonType.Grass, PokemonType.Poison),
        new(2, 32, EvolveMethod.LevelUp, 3, PokemonType.Grass, PokemonType.Poison),
        new(3, 32, EvolveMethod.None, 3, PokemonType.Grass, PokemonType.Poison),
        new(4, 16, EvolveMethod.LevelUp, 5, PokemonType.Fire, PokemonType.None),
        new(5, 36, EvolveMethod.LevelUp, 6, PokemonType.Fire, PokemonType.None),
        new(6, 36, EvolveMethod.None, 6, PokemonType.Fire, PokemonType.Flying),
        new(7, 16, EvolveMethod.LevelUp, 8, PokemonType.Water, PokemonType.None),
        new(8, 36, EvolveMethod.LevelUp, 9, PokemonType.Water, PokemonType.None),
        new(9, 36, EvolveMethod.None, 9, PokemonType.Water, PokemonType.None),
        new(10, 7, EvolveMethod.LevelUp, 11, PokemonType.Bug, PokemonType.None),
        new(11, 10, EvolveMethod.LevelUp, 12, PokemonType.Bug, PokemonType.None),
        new(12, 10, EvolveMethod.None, 12, PokemonType.Bug, PokemonType.Flying),
        new(13, 7, EvolveMethod.LevelUp, 10, PokemonType.Bug, PokemonType.Poison),
        new(14, 10, EvolveMethod.LevelUp, 15, PokemonType.Bug, PokemonType.Poison),
        new(15, 10, EvolveMethod.None, 15, PokemonType.Bug, PokemonType.Poison),
        new(16, 18, EvolveMethod.LevelUp, 17, PokemonType.Normal, PokemonType.Flying),
        new(17, 36, EvolveMethod.LevelUp, 18, PokemonType.Normal, PokemonType.Flying),
        new(18, 36, EvolveMethod.None, 18, PokemonType.Normal, PokemonType.Flying),
        new(19, 20, EvolveMethod.LevelUp, 20, PokemonType.Normal, PokemonType.None),
        new(20, 20, EvolveMethod.None, 20, PokemonType.Normal, PokemonType.None),
        new(21, 20, EvolveMethod.LevelUp, 22, PokemonType.Normal, PokemonType.Flying),
        new(22, 20, EvolveMethod.None, 22, PokemonType.Normal, PokemonType.Flying),
        new(23, 22, EvolveMethod.LevelUp, 24, PokemonType.Poison, PokemonType.None),
        new(24, 22, EvolveMethod.None, 24, PokemonType.Poison, PokemonType.None),
        new(25, 0, EvolveMethod.ThunderStone, 26, PokemonType.Electric, PokemonType.None),
        new(26, 0, EvolveMethod.None, 26, PokemonType.Electric, PokemonType.None),
        new(27, 22, EvolveMethod.LevelUp, 28, PokemonType.Ground, PokemonType.None),
        new(28, 22, EvolveMethod.None, 28, PokemonType.Ground, PokemonType.None),
        new(29, 16, EvolveMethod.LevelUp, 30, PokemonType.Poison, PokemonType.None),
        new(30, 0, EvolveMethod.MoonStone, 31, PokemonType.Poison, PokemonType.None),
        new(31, 0, EvolveMethod.None, 31, PokemonType.Poison, PokemonType.Ground),
        new(32, 16, EvolveMethod.LevelUp, 33, PokemonType.Poison, PokemonType.None),
        new(33, 0, EvolveMethod.MoonStone, 34, PokemonType.Poison, PokemonType.None),
        new(34, 0, EvolveMethod.None, 34, PokemonType.Poison, PokemonType.Ground),
        new(35, 0, EvolveMethod.MoonStone, 36, PokemonType.Fairy, PokemonType.None),
        new(36, 0, EvolveMethod.None, 36, PokemonType.Fairy, PokemonType.None),
        new(37, 0, EvolveMethod.FireStone, 38, PokemonType.Fire, PokemonType.None),
        new(38, 0, EvolveMethod.None, 38, PokemonType.Fire, PokemonType.None),
        new(39, 0, EvolveMethod.MoonStone, 40, PokemonType.Normal, PokemonType.Fairy),
        new(40, 0, EvolveMethod.None, 40, PokemonType.Normal, PokemonType.Fairy),
        new(41, 22, EvolveMethod.LevelUp, 42, PokemonType.Poison, PokemonType.Flying),
        new(42, 22, EvolveMethod.None, 42, PokemonType.Poison, PokemonType.Flying), //Update this later
        new(43, 21, EvolveMethod.LevelUp, 44, PokemonType.Grass, PokemonType.Poison),
        new(44, 0, EvolveMethod.LeafStone, 45, PokemonType.Grass, PokemonType.Poison), //Update this later
        new(45, 0, EvolveMethod.None, 45, PokemonType.Grass, PokemonType.Poison),
        new(46, 24, EvolveMethod.LevelUp, 47, PokemonType.Bug, PokemonType.Grass),
        new(47, 24, EvolveMethod.None, 47, PokemonType.Bug, PokemonType.Grass),
        new(48, 31, EvolveMethod.LevelUp, 49, PokemonType.Bug, PokemonType.Poison),
        new(49, 31, EvolveMethod.None, 49, PokemonType.Bug, PokemonType.Poison),
        new(50, 26, EvolveMethod.LevelUp, 51, PokemonType.Ground, PokemonType.None),
        new(51, 26, EvolveMethod.None, 51, PokemonType.Ground, PokemonType.None),
        new(52, 28, EvolveMethod.LevelUp, 53, PokemonType.Normal, PokemonType.None),
        new(53, 28, EvolveMethod.None, 53, PokemonType.Normal, PokemonType.None),
        new(54, 33, EvolveMethod.LevelUp, 55, PokemonType.Water, PokemonType.None),
        new(55, 33, EvolveMethod.None, 55, PokemonType.Water, PokemonType.None),
        new(56, 28, EvolveMethod.LevelUp, 57, PokemonType.Fighting, PokemonType.None),
        new(57, 28, EvolveMethod.None, 57, PokemonType.Fighting, PokemonType.None), //Update this later
        new(58, 0, EvolveMethod.FireStone, 59, PokemonType.Fire, PokemonType.None),
        new(59, 0, EvolveMethod.None, 59, PokemonType.Fire, PokemonType.None),
        new(60, 25, EvolveMethod.LevelUp, 61, PokemonType.Water, PokemonType.None),
        new(61, 0, EvolveMethod.WaterStone, 62, PokemonType.Water, PokemonType.None), //Update this later
        new(62, 0, EvolveMethod.None, 62, PokemonType.Water, PokemonType.Fighting),
        new(63, 16, EvolveMethod.LevelUp, 64, PokemonType.Psychic, PokemonType.None),
        new(64, 0, EvolveMethod.LinkingCable, 65, PokemonType.Psychic, PokemonType.None),
        new(65, 0, EvolveMethod.None, 65, PokemonType.Psychic, PokemonType.None),
        new(66, 28, EvolveMethod.LevelUp, 67, PokemonType.Fighting, PokemonType.None),
        new(67, 0, EvolveMethod.LinkingCable, 68, PokemonType.Fighting, PokemonType.None),
        new(68, 0, EvolveMethod.None, 68, PokemonType.Fighting, PokemonType.None),
        new(69, 21, EvolveMethod.LevelUp, 70, PokemonType.Grass, PokemonType.Poison),
        new(70, 0, EvolveMethod.LeafStone, 71, PokemonType.Grass, PokemonType.Poison),
        new(71, 0, EvolveMethod.None, 71, PokemonType.Grass, PokemonType.Poison),
        new(72, 30, EvolveMethod.LevelUp, 73, PokemonType.Water, PokemonType.Poison),
        new(73, 30, EvolveMethod.None, 73, PokemonType.Water, PokemonType.Poison),
        new(74, 25, EvolveMethod.LevelUp, 75, PokemonType.Rock, PokemonType.Ground),
        new(75, 0, EvolveMethod.LinkingCable, 76, PokemonType.Rock, PokemonType.Ground),
        new(76, 0, EvolveMethod.None, 76, PokemonType.Rock, PokemonType.Ground),
        new(77, 40, EvolveMethod.LevelUp, 78, PokemonType.Fire, PokemonType.None),
        new(78, 40, EvolveMethod.None, 78, PokemonType.Fire, PokemonType.None),
        new(79, 37, EvolveMethod.LevelUp, 80, PokemonType.Water, PokemonType.Psychic), //Update this later
        new(80, 37, EvolveMethod.None, 80, PokemonType.Water, PokemonType.Psychic),
        new(81, 30, EvolveMethod.LevelUp, 82, PokemonType.Electric, PokemonType.Steel),
        new(82, 30, EvolveMethod.None, 82, PokemonType.Electric, PokemonType.Steel), //Update this later
        new(83, 0, EvolveMethod.None, 82, PokemonType.Normal, PokemonType.Flying),
        new(84, 31, EvolveMethod.LevelUp, 85, PokemonType.Normal, PokemonType.Flying),
        new(85, 31, EvolveMethod.None, 85, PokemonType.Normal, PokemonType.Flying),
        new(86, 34, EvolveMethod.LevelUp, 87, PokemonType.Water, PokemonType.None),
        new(87, 34, EvolveMethod.None, 87, PokemonType.Water, PokemonType.Ice),
        new(88, 38, EvolveMethod.LevelUp, 89, PokemonType.Poison, PokemonType.None),
        new(89, 38, EvolveMethod.None, 89, PokemonType.Poison, PokemonType.None),
        new(90, 0, EvolveMethod.WaterStone, 91, PokemonType.Water, PokemonType.None),
        new(91, 0, EvolveMethod.None, 91, PokemonType.Water, PokemonType.Ice),
        new(92, 25, EvolveMethod.LevelUp, 93, PokemonType.Ghost, PokemonType.Poison),
        new(93, 0, EvolveMethod.LinkingCable, 94, PokemonType.Ghost, PokemonType.Poison),
        new(94, 0, EvolveMethod.None, 94, PokemonType.Ghost, PokemonType.Poison),
        new(95, 0, EvolveMethod.None, 95, PokemonType.Rock, PokemonType.Ground), //Update this later
        new(96, 26, EvolveMethod.LevelUp, 97, PokemonType.Psychic, PokemonType.None),
        new(97, 26, EvolveMethod.None, 97, PokemonType.Psychic, PokemonType.None),
        new(98, 28, EvolveMethod.LevelUp, 99, PokemonType.Water, PokemonType.None),
        new(99, 28, EvolveMethod.None, 99, PokemonType.Water, PokemonType.None),
        new(100, 30, EvolveMethod.LevelUp, 101, PokemonType.Electric, PokemonType.None),
        new(101, 30, EvolveMethod.None, 101, PokemonType.Electric, PokemonType.None),
        new(102, 0, EvolveMethod.LeafStone, 103, PokemonType.Grass, PokemonType.Psychic),
        new(103, 0, EvolveMethod.None, 103, PokemonType.Grass, PokemonType.Psychic),
        new(104, 28, EvolveMethod.LevelUp, 105, PokemonType.Ground, PokemonType.None),
        new(105, 28, EvolveMethod.None, 105, PokemonType.Ground, PokemonType.None),
        new(106, 0, EvolveMethod.None, 106, PokemonType.Fighting, PokemonType.None),
        new(107, 0, EvolveMethod.None, 107, PokemonType.Fighting, PokemonType.None),
        new(108, 0, EvolveMethod.None, 108, PokemonType.Normal, PokemonType.None), //Update this later
        new(109, 35, EvolveMethod.LevelUp, 110, PokemonType.Poison, PokemonType.None),
        new(110, 35, EvolveMethod.None, 110, PokemonType.Poison, PokemonType.None),
        new(111, 42, EvolveMethod.LevelUp, 112, PokemonType.Ground, PokemonType.Rock),
        new(112, 42, EvolveMethod.None, 112, PokemonType.Ground, PokemonType.Rock), //Update this later
        new(113, 0, EvolveMethod.None, 113, PokemonType.Normal, PokemonType.None), //Update this later
        new(114, 0, EvolveMethod.None, 114, PokemonType.Grass, PokemonType.None), //Update this later
        new(115, 0, EvolveMethod.None, 115, PokemonType.Normal, PokemonType.None),
        new(116, 32, EvolveMethod.LevelUp, 117, PokemonType.Water, PokemonType.None),
        new(117, 32, EvolveMethod.None, 117, PokemonType.Water, PokemonType.None), //Update this later
        new(118, 33, EvolveMethod.LevelUp, 119, PokemonType.Water, PokemonType.None),
        new(119, 32, EvolveMethod.None, 119, PokemonType.Water, PokemonType.None),
        new(120, 32, EvolveMethod.WaterStone, 121, PokemonType.Water, PokemonType.None),
        new(121, 32, EvolveMethod.None, 121, PokemonType.Water, PokemonType.Psychic),
        new(122, 0, EvolveMethod.None, 122, PokemonType.Psychic, PokemonType.Fairy),
        new(123, 0, EvolveMethod.None, 123, PokemonType.Bug, PokemonType.Flying), //Update this later
        new(124, 0, EvolveMethod.None, 124, PokemonType.Ice, PokemonType.Psychic),
        new(125, 0, EvolveMethod.None, 125, PokemonType.Electric, PokemonType.None), //Update this later
        new(126, 0, EvolveMethod.None, 126, PokemonType.Fire, PokemonType.None), //Update this later
        new(127, 0, EvolveMethod.None, 127, PokemonType.Bug, PokemonType.None),
        new(128, 0, EvolveMethod.None, 128, PokemonType.Normal, PokemonType.None),
        new(129, 20, EvolveMethod.LevelUp, 130, PokemonType.Water, PokemonType.None),
        new(130, 20, EvolveMethod.None, 130, PokemonType.Water, PokemonType.Flying),
        new(131, 0, EvolveMethod.None, 131, PokemonType.Water, PokemonType.Ice),
        new(132, 0, EvolveMethod.None, 132, PokemonType.Normal, PokemonType.None),
        new(133, 0, EvolveMethod.WaterStone, 134, PokemonType.Normal, PokemonType.None), //Update this later
        new(134, 0, EvolveMethod.None, 134, PokemonType.Water, PokemonType.None),
        new(135, 0, EvolveMethod.None, 135, PokemonType.Electric, PokemonType.None),
        new(136, 0, EvolveMethod.None, 136, PokemonType.Fire, PokemonType.None),
        new(137, 0, EvolveMethod.None, 137, PokemonType.Normal, PokemonType.None), //Update this later
        new(138, 40, EvolveMethod.LevelUp, 139, PokemonType.Rock, PokemonType.Water),
        new(139, 40, EvolveMethod.None, 139, PokemonType.Rock, PokemonType.Water),
        new(140, 40, EvolveMethod.LevelUp, 141, PokemonType.Rock, PokemonType.Water),
        new(141, 40, EvolveMethod.None, 141, PokemonType.Rock, PokemonType.Water),
        new(142, 0, EvolveMethod.None, 142, PokemonType.Rock, PokemonType.Flying),
        new(143, 0, EvolveMethod.None, 143, PokemonType.Normal, PokemonType.None),
        new(144, 0, EvolveMethod.None, 144, PokemonType.Ice, PokemonType.Flying),
        new(145, 0, EvolveMethod.None, 145, PokemonType.Electric, PokemonType.Flying),
        new(146, 0, EvolveMethod.None, 146, PokemonType.Fire, PokemonType.Flying),
        new(147, 30, EvolveMethod.LevelUp, 148, PokemonType.Dragon, PokemonType.None),
        new(148, 55, EvolveMethod.LevelUp, 149, PokemonType.Dragon, PokemonType.None),
        new(149, 55, EvolveMethod.None, 149, PokemonType.Dragon, PokemonType.Flying),
        new(150, 0, EvolveMethod.None, 150, PokemonType.Psychic, PokemonType.None),
        new(151, 0, EvolveMethod.None, 151, PokemonType.Psychic, PokemonType.None)
    };
    public static List<Pokemon> RegionalPokemonData = new List<Pokemon>()
    {
        new(0, 0, EvolveMethod.None, 0, PokemonType.None, PokemonType.None),
        new(19, 20, EvolveMethod.LevelUp, 20, PokemonType.Dark, PokemonType.Normal, RegionalForm.Alolan),
        new(20, 20, EvolveMethod.None, 20, PokemonType.Dark, PokemonType.Normal, RegionalForm.Alolan),
        new(25, 0, EvolveMethod.ThunderStone, 26, PokemonType.Electric, PokemonType.None, RegionalForm.Alolan),
        new(26, 0, EvolveMethod.None, 26, PokemonType.Electric, PokemonType.Psychic, RegionalForm.Alolan),
        new(27, 0, EvolveMethod.IceStone, 28, PokemonType.Ice, PokemonType.Steel, RegionalForm.Alolan),
        new(28, 0, EvolveMethod.None, 28, PokemonType.Ice, PokemonType.Steel, RegionalForm.Alolan),
        new(37, 0, EvolveMethod.IceStone, 38, PokemonType.Ice, PokemonType.None, RegionalForm.Alolan),
        new(38, 0, EvolveMethod.None, 38, PokemonType.Ice, PokemonType.Fairy, RegionalForm.Alolan),
        new(50, 26, EvolveMethod.LevelUp, 51, PokemonType.Ground, PokemonType.Steel, RegionalForm.Alolan),
        new(51, 26, EvolveMethod.None, 51, PokemonType.Ground, PokemonType.Steel, RegionalForm.Alolan),
        new(52, 0, EvolveMethod.LvlUpFriendshipToken, 53, PokemonType.Dark, PokemonType.None, RegionalForm.Alolan),
        new(52, 0, EvolveMethod.None, 53, PokemonType.Steel, PokemonType.None, RegionalForm.Galarian), //Update this later
        new(53, 28, EvolveMethod.None, 53, PokemonType.Dark, PokemonType.None, RegionalForm.Alolan),
        new(58, 0, EvolveMethod.FireStone, 59, PokemonType.Fire, PokemonType.Rock, RegionalForm.Hisuian),
        new(59, 0, EvolveMethod.None, 59, PokemonType.Fire, PokemonType.Rock, RegionalForm.Hisuian),
        new(74, 25, EvolveMethod.LevelUp, 75, PokemonType.Rock, PokemonType.Electric, RegionalForm.Alolan),
        new(75, 0, EvolveMethod.LinkingCable, 76, PokemonType.Rock, PokemonType.Electric, RegionalForm.Alolan),
        new(76, 0, EvolveMethod.None, 76, PokemonType.Rock, PokemonType.Electric, RegionalForm.Alolan),
        new(77, 40, EvolveMethod.LevelUp, 78, PokemonType.Psychic, PokemonType.None, RegionalForm.Galarian),
        new(78, 40, EvolveMethod.None, 78, PokemonType.Psychic, PokemonType.Fairy, RegionalForm.Galarian),
        new(79, 37, EvolveMethod.GalaricaCuff, 80, PokemonType.Poison, PokemonType.Psychic, RegionalForm.Galarian), //Update this later
        new(80, 37, EvolveMethod.None, 80, PokemonType.Psychic, PokemonType.None, RegionalForm.Galarian),
        new(83, 0, EvolveMethod.None, 82, PokemonType.Fighting, PokemonType.None, RegionalForm.Galarian), //Update this later
        new(88, 38, EvolveMethod.LevelUp, 89, PokemonType.Poison, PokemonType.Dark, RegionalForm.Alolan),
        new(89, 38, EvolveMethod.None, 89, PokemonType.Poison, PokemonType.Dark, RegionalForm.Alolan),
        new(100, 30, EvolveMethod.LevelUp, 101, PokemonType.Electric, PokemonType.Grass, RegionalForm.Hisuian),
        new(101, 30, EvolveMethod.None, 101, PokemonType.Electric, PokemonType.Grass, RegionalForm.Hisuian),
        new(102, 0, EvolveMethod.LeafStone, 103, PokemonType.Grass, PokemonType.Psychic, RegionalForm.Alolan),
        new(103, 0, EvolveMethod.None, 103, PokemonType.Grass, PokemonType.Dragon, RegionalForm.Alolan),
        new(104, 28, EvolveMethod.LevelUp, 105, PokemonType.Ground, PokemonType.None, RegionalForm.Alolan),
        new(105, 0, EvolveMethod.None, 105, PokemonType.Fire, PokemonType.Ghost, RegionalForm.Alolan),
        new(109, 35, EvolveMethod.LevelUp, 110, PokemonType.Poison, PokemonType.None, RegionalForm.Galarian),
        new(110, 35, EvolveMethod.None, 110, PokemonType.Poison, PokemonType.None, RegionalForm.Galarian),
        new(122, 0, EvolveMethod.None, 122, PokemonType.Ice, PokemonType.Psychic, RegionalForm.Galarian), //Update this later
        new(128, 0, EvolveMethod.None, 128, PokemonType.Normal, PokemonType.None, RegionalForm.Paldean, StaticPokemonForms.CombatBreed),
        new(144, 0, EvolveMethod.None, 144, PokemonType.Psychic, PokemonType.Flying, RegionalForm.Galarian),
        new(145, 0, EvolveMethod.None, 145, PokemonType.Fighting, PokemonType.Flying, RegionalForm.Galarian),
        new(146, 0, EvolveMethod.None, 146, PokemonType.Dark, PokemonType.Flying, RegionalForm.Galarian),
    };
    public static List<Pokemon> StaticFormPokemonData = new List<Pokemon>()
    {
        new(0, 0, EvolveMethod.None, 0, PokemonType.None, PokemonType.None),
        new(128, 0, EvolveMethod.None, 0, PokemonType.Fighting, PokemonType.None, RegionalForm.Paldean, StaticPokemonForms.BlazeBreed),
        new(128, 0, EvolveMethod.None, 0, PokemonType.Fighting, PokemonType.None, RegionalForm.Paldean, StaticPokemonForms.AquaBreed),
        //new(201, 0, EvolveMethod.None, 0, PokemonType.Psychic, PokemonType.None, RegionalForm.None, StaticPokemonForms.A)

    };
}
